services:
  toko-patria:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: toko-patria
    ports:
      - "8000:8000"
    volumes:
      - ./.env:/app/.env
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - homelabs

networks:
  homelabs:
    external: true